### PR TITLE
Creating pages to set/reset password

### PR DESCRIPTION
**Pull request by melinashak-noaa**
Thinking of putting the password and username pages in boatnet-modules/bn-auth so boatnet will be able to use these screens as well. Not sure if that will work though, tried getting it to work with the yarn link, but didn't have any success, think I may need to publish to npm. Also started looking into other ways to share components between projects, maybe we could try this if npm doesn't work anyways open to ideas. 

https://blog.bitsrc.io/how-to-easily-share-vue-components-between-applications-1d30a1ad4e4d

### CODE REVIEW

**Review by sethgerou-noaa — APPROVED** [review]
looks good.  So far this seems like it could live in bn-common with other shared components (nothing we need to keep private/hidden).

**Comment by melinashak-noaa** [comment]
yes, but this is currently in the research catch repo which doesn't have access to the bn-common components in the boatnet repo

**Comment by sethgerou-noaa** [comment]
oh right.  well, I guess it might be more trouble than it's worth to share the front end code.  The back end code is where sharing will be most valuable I think.

**Comment by melinashak-noaa** [comment]
Just updated this, and [bn-modules/bn-auth](https://github.com/nwfsc-fram/boatnet-module/pull/167/files) to call the new stored procedures

**Pull request merged**
